### ISSUE TITLE
Opening connection stucks client while connecting to server on non listened port

### ISSUE THREAD

**Issue by hydridity** [ShadowKatStudios/OC-Minitel#30]
In situation where server's computer minitel daemon is running and the server is not listening to any ports, client trying to open a connection to any port on this server will result client's open function to never return
https://github.com/ShadowKatStudios/OC-Minitel/blob/ddf3a9b17db7882b386fc7d61d96d7f60a0ad317/OpenOS/usr/lib/minitel.lua#L110-L135
I've identified the problem as following:
Because the server daemon is running it will respond with ack for "openstream" request packet resulting in net.open function to pass condition on line 111 following to line 115 where it's waiting for "net_msg" event, but because the requested  server is not listening to this port this event is never fired up resulting the client application to infinitely pulling this event on line 115 and probably only time it will exit is while getting too long without yelding system error
I've been able to temporary fix this by adding timeout to this event to be same as configured streamdelay or any timeout limit

`_,from,rport,data = event.pull(st, "net_msg") `

that will at least return back with timeout error according to condition on line 122

I've been thinking this could be fixed by implementing some kind of accept/refuse packet mechanism inside the daemon where at the beggining of library listen function internal computer event will be sent to daemon to register opened port and function that will react to layer 5 "openstream" requests and respond with accept or refuse type packet depending if the port is registered by listen function
But is would it be valid approach with project functionality in mind ?

**Comment by XeonSquared** [comment]
I'm not entirely against adding a negative acknowledgement, but I'm mildly concerned that it may make port scanning a more practical affair. At any rate, that should fix the issue with never returning.
