### ISSUE TITLE
Documentation for OpenOS?

### ISSUE THREAD

**Issue by skyem123** [ShadowKatStudios/OC-Minitel#4]
Maybe it would be worth it to have user guides in markdown, and also to put those user guides and documentation specifications as help from within OpenOS using the `man` command?

**Comment by XeonSquared** [comment]
Yeah, this is a good idea. Do we want to try to automatically convert to man pages or just do the formatting ourselves?

**Comment by skyem123** [comment]
I would just copy the markdown. :p
OpenOS man files are not as feature full as Linux man files.

**Comment by XeonSquared** [comment]
Bit late to close this but I think it's more or less done, for the core daemon at least.
